workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      vars:
        XCODE_WORKSPACE: "BookMate.xcworkspace"
        XCODE_SCHEME: "BookMate"
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          if [ -f "Podfile" ]; then
            pod install
          fi
      - name: Build iOS app for simulator (no signing required)
        script: |
          xcodebuild build -workspace "$XCODE_WORKSPACE" -scheme "$XCODE_SCHEME" \
            -configuration Debug \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest'
    artifacts:
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM